# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setObjectName("nextBtn")
        self.gridLayout.addWidget(self.nextBtn, 1, 2, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 3)
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBtn.setObjectName("pauseBtn")
        self.gridLayout.addWidget(self.pauseBtn, 1, 5, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 1, 6, 1, 1)
        self.playBtn = QtWidgets.QPushButton(self.centralwidget)
        self.playBtn.setObjectName("playBtn")
        self.gridLayout.addWidget(self.playBtn, 1, 4, 1, 1)
        self.videoWidget = QtWidgets.QLabel(self.centralwidget)
        self.videoWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.videoWidget.setText("")
        self.videoWidget.setScaledContents(True)
        self.videoWidget.setAlignment(QtCore.Qt.AlignCenter)
        self.videoWidget.setObjectName("videoWidget")
        self.gridLayout.addWidget(self.videoWidget, 0, 0, 1, 7)
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setObjectName("prevBtn")
        self.gridLayout.addWidget(self.prevBtn, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nextBtn.setText(_translate("MainWindow", "Next Frame"))
        self.btnBrowse.setText(_translate("MainWindow", "Выберите файл"))
        self.checkBox.setText(_translate("MainWindow", "Цветное изображение"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.playBtn.setText(_translate("MainWindow", "Play"))
        self.prevBtn.setText(_translate("MainWindow", "Prev Frame"))
